env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - 'standard'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    impliedStrict: true
    jsx: true
  ecmaVersion: 7
  sourceType: module
parser: 'babel-eslint'
plugins:
  - react
globals:
  beforeEach: true
  describe: true
  expect: true
  it: true
  React: true
  xdescribe: true
  xit: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-function-paren:
    - error
    - never
  react/prop-types:
    - off
  comma-dangle:
    - error
    - always-multiline
  generator-star-spacing:
    - error
    - after
