# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 16:20
from __future__ import unicode_literals

from django.db import migrations
import djangoapps.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170427_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock()), ('richtext', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', djangoapps.pages.blocks.ReactImageChooserBlock()))),
        ),
    ]
